### ISSUE TITLE
Please add me to contributors list

### ISSUE THREAD

**Issue by frankly034** [hnginterns/hngfun#69]
Slack: franklynugege
Git: franly033

**Comment by frankly034** [comment]
Git: frankly034

**Comment by Rhodinet** [comment]
I added franklynugege (franly033) as he requested twice.
Please from the admin if it alters anything let everyone know on the appropriate channel for changes.

**Comment by frankly034** [comment]
Good morning, my phone made an auto correct to my user name
on slack its franklynugege
on git its franly034

I'm sorry for this error.

I've been trying to make the changes.

**Comment by victorkanu84** [comment]
Please add me to the contributors list. 
Slack:victorkanu84
Git:victorkanu84

**Comment by lurdmark** [comment]
Please add me to contributors list
Slack:lurdmark
Git:lurdmark
